import { NextRequest, NextResponse } from 'next/server';
import pool from '../../../../lib/db';

interface RawOrderData {
  order_id: number;
  user_name: string;
  user_city?: string;
  email: string;
  mobile: string;
  whatsapp_number?: string;
  address: string;
  items: string; // JSON string of cart items
  created_at?: number;
}

// GET /api/orders/raw - List raw orders with pagination
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1', 10);
    const limit = parseInt(searchParams.get('limit') || '10', 10);
    const offset = (page - 1) * limit;
    
    const email = searchParams.get('email');
    const mobile = searchParams.get('mobile');
    const orderId = searchParams.get('order_id');

    const connection = await pool.getConnection();
    
    try {
      let whereClause = '';
    const queryParams: (string | number)[] = [];
    
    if (email || mobile || orderId) {
      const conditions: string[] = [];
      if (email) {
        conditions.push('email LIKE ?');
        queryParams.push(`%${email}%`);
      }
      if (mobile) {
        conditions.push('mobile LIKE ?');
        queryParams.push(`%${mobile}%`);
      }
      if (orderId) {
        conditions.push('order_id = ?');
        queryParams.push(parseInt(orderId, 10));
      }
      whereClause = 'WHERE ' + conditions.join(' AND ');
    }
      
      // Get total count
      const countQuery = `SELECT COUNT(*) as total FROM af_guestordersraws ${whereClause}`;
      const [countResult] = await connection.execute(countQuery, queryParams);
      const total = (countResult as { total: number }[])[0].total;
      
      // Get paginated results
      const dataQuery = `
        SELECT * FROM af_guestordersraws 
        ${whereClause}
        ORDER BY created_at DESC 
        LIMIT ? OFFSET ?
      `;
      const [rows] = await connection.execute(dataQuery, [...queryParams, limit, offset]);
      
      return NextResponse.json({
        success: true,
        data: rows,
        pagination: {
          page,
          limit,
          total,
          totalPages: Math.ceil(total / limit)
        }
      });
      
    } finally {
      connection.release();
    }
    
  } catch (error) {
    console.error('Error fetching raw orders:', error);
    return NextResponse.json(
      {
        success: false,
        message: 'Failed to fetch raw orders',
        error: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

// POST /api/orders/raw - Create a new raw order entry
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // Validate required fields (order_id is auto-generated by database)
    const requiredFields = ['user_name', 'email', 'mobile', 'address', 'items'];
    for (const field of requiredFields) {
      if (!body[field]) {
        return NextResponse.json(
          {
            success: false,
            message: `Missing required field: ${field}`
          },
          { status: 400 }
        );
      }
    }
    
    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(body.email)) {
      return NextResponse.json(
        {
          success: false,
          message: 'Invalid email format'
        },
        { status: 400 }
      );
    }
    
    // Validate items is a valid JSON string
    try {
      JSON.parse(body.items);
    } catch {
      return NextResponse.json(
        {
          success: false,
          message: 'Items field must be a valid JSON string'
        },
        { status: 400 }
      );
    }
    
    const connection = await pool.getConnection();
    
    try {
      const now = new Date();
      
      const insertQuery = `
        INSERT INTO af_guestordersraws (
          user_name, user_city, email, mobile, 
          whatsapp_number, address, items, created_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
      `;
      
      const values = [
        body.user_name,
        body.user_city || null,
        body.email,
        body.mobile,
        body.whatsapp_number || null,
        body.address,
        body.items,
        now
      ];
      
      const [result] = await connection.execute(insertQuery, values);
      const insertId = (result as any).insertId;
      
      // Get the created raw order using the auto-generated order_id
      const selectQuery = 'SELECT * FROM af_guestordersraws WHERE order_id = ?';
      const [createdOrder] = await connection.execute(selectQuery, [insertId]);
      
      return NextResponse.json(
        {
          success: true,
          message: 'Raw order created successfully',
          data: (createdOrder as RawOrderData[])[0]
        },
        { status: 201 }
      );
      
    } finally {
      connection.release();
    }
    
  } catch (error) {
    console.error('Error creating raw order:', error);
    return NextResponse.json(
      {
        success: false,
        message: 'Failed to create raw order',
        error: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}